version: '3.7'

services:
  example:
    build:
      context: ./example
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./example:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev