version: '3.7'

services:
  example:
    build: 
      context: ./example
      dockerfile: Dockerfile.prod
    command: gunicorn example.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/example/staticfiles
      - media_volume:/home/app/example/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/example/staticfiles
      - media_volume:/home/app/example/mediafiles
    ports:
      - 8081:80
    depends_on:
      - example
volumes:
  static_volume:
  media_volume:
